version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pdftoquiz:pdftoquiz@db:5432/pdftoquiz
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pdftoquiz
      - POSTGRES_PASSWORD=pdftoquiz
      - POSTGRES_DB=pdftoquiz
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 